export const theme = {
  colors: {
    red: "#F41B3B",
    green: "#1EBC99",
    blue: "#1884F7",
    yellow: "#F9CC0D",
    black: "#0A070B",
    darkGray: "#363536",
    mediumGray: "#4F4E50",
    lightGray: "#E8ECEF",
    white: "#FFF",
  },
  fontFamily: {
    light: "'GilroyLight', 'sans-serif",
    regular: "'GilroyRegular', 'sans-serif",
    medium: "'GilroyMedium', 'sans-serif",
    bold: "'GilroyBold', 'sans-serif'",
    extraBold: "'GilroyExtraBold', 'sans-serif'",
  },
  spacing: {
    xs: "8px",
    sm: "12px",
    md: "16px",
    lg: "24px",
    xl: "32px",
    xxl: "40px",
    xxxl: "48px",
    xxxxl: "56px",
    xxxxxl: "64px",
  },
};
